version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
#No se necesita bucket. Se emplea parámetro --resolve-s3 desde Pipeline
#s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
#No se necesita bucket. Se emplea parámetro --resolve-s3 desde Pipeline
#s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
#No se necesita bucket. Se emplea parámetro --resolve-s3 desde Pipeline
#s3_bucket = "aws-sam-cli-managed-production-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
